#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Brendan Shanahan | Physicist | IPP Greifswald
url: 'bshanahan.github.io'
baseurl: '//bshanahan.github.io' #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
tagline: Researcher in the stellarator theory department at the Institute for Plasma Physics, Greifswald
author: Brendan Shanahan

# Tracker
analytics: UA-168573225-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-seo-tag
  
# Development Settings
port: 4000
host: 0.0.0.0
safe: false